### ISSUE TITLE
GitHub page issues

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/user-guidance#82]
There are a number of issues on the GitHub section of the guidance:
- The link to s3 buckets in the first paragraph gives a 404. It should link to https://user-guidance.services.alpha.mojanalytics.xyz/data/amazon-s3/#content
- The link to "configure your username and email in Git on the analytical platform" doesn't work, because of a typo in the heading it should be linking to ("configure you username")
- You can now set repos as internal, which I think should be the default rather than private. The gif and guidance should be updated to reflect the expanded options for repo visibility
- The link in "For more info, see choosing public or private repos." doesn't go anywhere
- Github's UI has changed since the gifs were created, so they should be updated.

**Comment by katharinebreeze** [comment]
On the gifs - I find them quite difficult to follow as if you want to do each step one by one you have to keep waiting for them to go back to the beginning. I think adding accompanying instructions in the text would help.

**Comment by pjooman** [comment]
Re the gifs - another option would be having videos instead of gifs so they can be paused. Other issues I found:
- The link in the second line of the first para on the page "secrets" links to an MoJ policy document at the bottom of the page, but this second link didn't work for me
- Step 2 says to go to Settings and "Collaborators & Teams". That doesn't seem to exist. Guidance on what setting the repo to "internal" means would be appreciated - presumably this means that MoJ members can see my code, do I have to separately specify elsewhere who can make changes to it?
- When setting up a repo there is now an option to include a gitignore file. Some guidance on whether to do this would be helpful because there is a dropdown and I'm not sure what the options mean. Perhaps the "safety barriers" already in place mean this isn't needed, but I wasn't sure
- Some of the training resources links didn't work for me - the "basic tutorial" link redirected to a generic GitHub page, as did the "Introductory interactive tutorial"
Thanks in advance to those looking at this!

**Comment by neillturner** [comment]
fixed by Various documentation fixes for outstanding Issues #193
